"use strict";

window.MindEntryKeywordStore = (function () {
  var mfo = [
  "loop",
  "looping",
  "looping thoughts",
  "thoughts are looping",
  "my mind is looping",
  "can't stop thinking",
  "keep thinking",
  "over and over",
  "again and again",
  "replaying",
  "replay",
  "why did i",
  "why did i say that",
  "shouldn't have",
  "regret",
  "embarrassing",
  "stuck in my head",
  "can't let it go",
  "won't let go",
  "still thinking about it",
  "keeps replaying",
  "i keep replaying it",
  "ruminating",
  "rumination",
  "why did i say",
  "why did i do that",
  "i can't stop thinking about",
  "i keep thinking about",
  "it keeps replaying",
  "i keep replaying",
  "this keeps coming back",
  "it won't leave my head",
  "i can't let it go",
  "this is embarrassing",
  "i shouldn't have said",
  "i shouldn't have done",
  "cringe",
  "cringe memory",
  "self-criticism",
  "haven't accomplished",
  "comparing",
  "comparison",
  "falling behind",
  "simulating an argument",
  "pre-exhausted",
  "swallowing anger",
  "can't speak",
  "furious",
  "argument continues in my head",
  "irritating",
  "sticky",
  "sticky thought",
  "gain momentum",
  "starting to gain momentum",
  "not big yet",
  "early sour",
  "ループ",
  "ぐるぐる",
  "思考が止まらない",
  "考えが止まらない",
  "何度も考える",
  "何回も考える",
  "ずっと考えてしまう",
  "頭から離れない",
  "引きずってる",
  "なんであんなこと言ったんだろう",
  "なんであんなことしたんだろう",
  "言わなきゃよかった",
  "しなければよかった",
  "後悔",
  "恥ずかしい",
  "思い返してしまう",
  "何度も思い出す",
  "頭の中で繰り返す",
  "リプレイ",
  "考えすぎ",
  "schleife",
  "gedankenschleife",
  "es wiederholt sich",
  "ich kann nicht aufhören daran zu denken",
  "ich denke immer wieder daran",
  "immer wieder",
  "wieder und wieder",
  "replay",
  "warum habe ich das gesagt",
  "hätte ich das nicht gesagt",
  "hätte ich das nicht tun sollen",
  "bereue",
  "peinlich",
  "geht mir nicht aus dem kopf",
  "ich kann es nicht loslassen",
  "es lässt mich nicht los",
  "ich denke immer noch daran",
  "ich spiele es immer wieder durch",
  "grüble",
  "grübeln",
  "루프",
  "반복",
  "계속 생각나",
  "계속 생각하게 돼",
  "생각이 멈추지 않아",
  "계속 맴돌아",
  "자꾸 떠올라",
  "머리에서 안 떠나",
  "왜 그런 말을 했을까",
  "왜 그랬을까",
  "그러지 말걸",
  "말하지 말걸",
  "후회",
  "창피해",
  "계속 되새기고 있어",
  "자꾸 복기해",
  "놓아지지 않아",
  "아직도 생각 중이야",
  "계속 반복돼",
  "생각이 꼬리를 물어",
  "boucle",
  "ça tourne en boucle",
  "je n'arrête pas d'y penser",
  "j'y pense sans arrêt",
  "encore et encore",
  "ça repasse en boucle",
  "rejouer",
  "replay",
  "pourquoi j'ai dit ça",
  "j'aurais pas dû",
  "je regrette",
  "c'est embarrassant",
  "ça ne me sort pas de la tête",
  "je n'arrive pas à lâcher",
  "ça me hante",
  "j'y pense encore",
  "je repasse ça dans ma tête",
  "rumination",
  "je rumine",
  "loop",
  "em looping",
  "minha mente está em looping",
  "não consigo parar de pensar",
  "fico pensando nisso",
  "de novo e de novo",
  "de novo",
  "repassando",
  "replay",
  "por que eu disse isso",
  "não devia ter",
  "me arrependo",
  "que vergonha",
  "não sai da minha cabeça",
  "não consigo soltar",
  "não me larga",
  "ainda estou pensando nisso",
  "fico revivendo isso",
  "ruminando",
  "ruminação",
  "bucle",
  "en bucle",
  "mi mente está en bucle",
  "no puedo dejar de pensar",
  "sigo pensando en ello",
  "una y otra vez",
  "otra vez",
  "replay",
  "repetirlo en mi cabeza",
  "por qué dije eso",
  "no debería haberlo dicho",
  "me arrepiento",
  "qué vergüenza",
  "no se me va de la cabeza",
  "no puedo soltarlo",
  "no me deja en paz",
  "todavía sigo pensando en eso",
  "lo sigo repitiendo",
  "rumiando",
  "rumiación"
];
  var mso = [
  "need to",
  "have to",
  "don't forget",
  "remember to",
  "call",
  "email",
  "send",
  "schedule",
  "buy",
  "pick up",
  "reply",
  "waiting for a reply",
  "waiting for reply",
  "hasn't been answered",
  "check for reply",
  "check-in time",
  "later",
  "tomorrow",
  "remind",
  "set a reminder",
  "should do",
  "must do",
  "appointment",
  "invoice",
  "report",
  "deadline",
  "submit",
  "book",
  "renew",
  "pay",
  "task",
  "to do",
  "unfinished",
  "i need to",
  "i have to",
  "don't forget to",
  "remember to",
  "i should probably",
  "i should send",
  "i should call",
  "unproductive",
  "day off",
  "should be doing",
  "bottle them up",
  "review time",
  "compulsive check",
  "check again",
  "i should reply",
  "i should schedule",
  "i should book",
  "i should buy",
  "i should renew",
  "i should finish",
  "i should submit",
  "i should pay",
  "しなきゃ",
  "しないと",
  "やらなきゃ",
  "やらないと",
  "忘れないように",
  "覚えておく",
  "電話",
  "メール",
  "送る",
  "予約",
  "買う",
  "迎えに行く",
  "返信",
  "あとで",
  "明日",
  "リマインド",
  "予定",
  "締切",
  "提出",
  "支払う",
  "更新",
  "タスク",
  "やること",
  "未完了",
  "muss",
  "muss noch",
  "ich muss",
  "nicht vergessen",
  "daran denken",
  "anrufen",
  "mailen",
  "schicken",
  "einplanen",
  "kaufen",
  "abholen",
  "antworten",
  "später",
  "morgen",
  "erinnern",
  "erinnerung",
  "termin",
  "rechnung",
  "bericht",
  "frist",
  "einreichen",
  "buchen",
  "verlängern",
  "bezahlen",
  "aufgabe",
  "to do",
  "offen",
  "해야 해",
  "해야지",
  "해야겠다",
  "잊지 말아야 해",
  "기억해야 해",
  "전화",
  "메일",
  "보내기",
  "일정",
  "사야 해",
  "데리러 가기",
  "답장",
  "나중에",
  "내일",
  "알림",
  "리마인더",
  "약속",
  "마감",
  "제출",
  "예약",
  "갱신",
  "결제",
  "할 일",
  "미완료",
  "je dois",
  "il faut que",
  "ne pas oublier",
  "penser à",
  "appeler",
  "envoyer un mail",
  "envoyer",
  "planifier",
  "acheter",
  "aller chercher",
  "répondre",
  "plus tard",
  "demain",
  "rappel",
  "mettre un rappel",
  "rendez-vous",
  "facture",
  "rapport",
  "date limite",
  "soumettre",
  "réserver",
  "renouveler",
  "payer",
  "tâche",
  "à faire",
  "non terminé",
  "preciso",
  "tenho que",
  "não esquecer",
  "lembrar de",
  "ligar",
  "mandar email",
  "enviar",
  "agendar",
  "comprar",
  "buscar",
  "responder",
  "depois",
  "amanhã",
  "lembrete",
  "colocar um lembrete",
  "consulta",
  "fatura",
  "relatório",
  "prazo",
  "entregar",
  "reservar",
  "renovar",
  "pagar",
  "tarefa",
  "a fazer",
  "inacabado",
  "necesito",
  "tengo que",
  "no olvidar",
  "acordarme de",
  "llamar",
  "enviar correo",
  "enviar",
  "programar",
  "comprar",
  "recoger",
  "responder",
  "luego",
  "mañana",
  "recordatorio",
  "poner un recordatorio",
  "cita",
  "factura",
  "informe",
  "plazo",
  "entregar",
  "reservar",
  "renovar",
  "pagar",
  "tarea",
  "pendiente",
  "sin terminar"
];
  var mzo = [
  "too much",
  "too many",
  "overwhelmed",
  "can't focus",
  "everything",
  "my head",
  "busy",
  "too much in my head",
  "obsessively checking",
  "checking my phone",
  "overstimulated",
  "heart racing",
  "panic",
  "pre-presentation",
  "my brain is full",
  "brain is full",
  "overstimulated",
  "too much input",
  "need a break",
  "need space",
  "can't think straight",
  "too noisy",
  "my mind is noisy",
  "scattered",
  "i need to zone out",
  "shut everything out",
  "too many things",
  "everything at once",
  "there's too much going on",
  "i need to pause",
  "i need to disconnect",
  "多すぎる",
  "いっぱいいっぱい",
  "圧倒される",
  "集中できない",
  "頭がいっぱい",
  "頭の中がうるさい",
  "考えが多すぎる",
  "刺激が多すぎる",
  "疲れた",
  "休みたい",
  "スペースがほしい",
  "何もしたくない",
  "ぼーっとしたい",
  "静かにしたい",
  "頭がパンパン",
  "情報が多すぎる",
  "散らかってる",
  "zu viel",
  "zu viele",
  "überfordert",
  "ich kann mich nicht konzentrieren",
  "alles",
  "mein kopf ist voll",
  "zu viel im kopf",
  "mein gehirn ist voll",
  "überreizt",
  "zu viel input",
  "ich brauche eine pause",
  "ich brauche ruhe",
  "ich kann nicht klar denken",
  "zu laut",
  "mein kopf ist laut",
  "verstreut",
  "ich will einfach abschalten",
  "nichts mehr aufnehmen",
  "너무 많아",
  "너무 많다",
  "벅차",
  "압도돼",
  "집중이 안 돼",
  "머리가 꽉 찼어",
  "머릿속이 복잡해",
  "생각이 너무 많아",
  "자극이 너무 많아",
  "쉬고 싶어",
  "공간이 필요해",
  "가만히 있고 싶어",
  "멍 때리고 싶어",
  "조용해지고 싶어",
  "정보가 너무 많아",
  "산만해",
  "trop",
  "trop de choses",
  "débordé",
  "je n'arrive pas à me concentrer",
  "ma tête est pleine",
  "trop dans ma tête",
  "mon cerveau est plein",
  "surstimulé",
  "trop de stimulation",
  "j'ai besoin d'une pause",
  "j'ai besoin d'espace",
  "je n'arrive pas à penser clairement",
  "trop de bruit",
  "mon esprit est bruyant",
  "éparpillé",
  "j'ai besoin de décrocher",
  "demais",
  "coisa demais",
  "sobrecarregado",
  "não consigo focar",
  "minha cabeça está cheia",
  "muita coisa na cabeça",
  "meu cérebro está cheio",
  "superestimulado",
  "estímulo demais",
  "preciso de uma pausa",
  "preciso de espaço",
  "não consigo pensar direito",
  "barulho demais",
  "minha mente está barulhenta",
  "disperso",
  "quero desligar",
  "demasiado",
  "demasiadas cosas",
  "abrumado",
  "no puedo concentrarme",
  "tengo la cabeza llena",
  "demasiado en la cabeza",
  "mi cerebro está lleno",
  "sobreestimulado",
  "demasiado estímulo",
  "necesito un descanso",
  "necesito espacio",
  "no puedo pensar con claridad",
  "demasiado ruido",
  "mi mente está ruidosa",
  "disperso",
  "quiero desconectar"
];
  var mbo = [
  "work",
  "client",
  "boss",
  "team",
  "meeting",
  "deadline",
  "parent",
  "kids",
  "family",
  "responsibility",
  "expecting",
  "pressure",
  "i can't afford to slow down",
  "always on",
  "i have to stay on",
  "i can't let them down",
  "i don't want to disappoint them",
  "i need to keep performing",
  "role",
  "identity",
  "can't switch off",
  "can't stop thinking about work",
  "everyone needs me",
  "they need me",
  "i can't disappoint them",
  "everyone expects",
  "everyone needs me",
  "i have to keep going",
  "i have to perform",
  "i can't switch off",
  "i can't stop working",
  "i'm always on",
  "too much responsibility",
  "i can't let them down",
  "仕事",
  "クライアント",
  "上司",
  "チーム",
  "会議",
  "締切",
  "親",
  "子ども",
  "家族",
  "責任",
  "期待",
  "プレッシャー",
  "立ち止まる余裕なんてない",
  "常時オン",
  "気を抜けない",
  "期待を裏切れない",
  "がっかりさせたくない",
  "ちゃんとやらなきゃ",
  "役割",
  "アイデンティティ",
  "仕事モードが切れない",
  "頭が仕事から離れない",
  "みんなが自分を必要としてる",
  "休めない",
  "arbeit",
  "kunde",
  "chef",
  "team",
  "meeting",
  "frist",
  "eltern",
  "kinder",
  "familie",
  "verantwortung",
  "erwartung",
  "druck",
  "ich kann es mir nicht leisten langsamer zu werden",
  "immer an",
  "ich muss funktionieren",
  "ich kann sie nicht enttäuschen",
  "ich will niemanden enttäuschen",
  "ich muss weiter leisten",
  "rolle",
  "identität",
  "ich kann nicht abschalten",
  "ich komme nicht aus dem arbeitsmodus",
  "alle brauchen mich",
  "일",
  "고객",
  "상사",
  "팀",
  "회의",
  "마감",
  "부모",
  "아이들",
  "가족",
  "책임",
  "기대",
  "압박",
  "멈출 여유가 없어",
  "항상 켜져 있어",
  "계속 버텨야 해",
  "실망시키면 안 돼",
  "실망시키고 싶지 않아",
  "계속 잘해야 해",
  "역할",
  "정체성",
  "꺼질 수가 없어",
  "일 모드에서 못 빠져나오겠어",
  "다들 나를 필요로 해",
  "travail",
  "client",
  "patron",
  "équipe",
  "réunion",
  "date limite",
  "parent",
  "enfants",
  "famille",
  "responsabilité",
  "attentes",
  "pression",
  "je ne peux pas me permettre de ralentir",
  "toujours actif",
  "je dois rester performant",
  "je ne peux pas les décevoir",
  "je ne veux pas les décevoir",
  "je dois continuer à assurer",
  "rôle",
  "identité",
  "je n'arrive pas à décrocher",
  "je n'arrive pas à quitter le mode travail",
  "tout le monde a besoin de moi",
  "trabalho",
  "cliente",
  "chefe",
  "equipe",
  "reunião",
  "prazo",
  "pai",
  "mãe",
  "filhos",
  "família",
  "responsabilidade",
  "expectativa",
  "pressão",
  "eu não posso me dar ao luxo de desacelerar",
  "sempre ligado",
  "tenho que continuar rendendo",
  "não posso decepcionar",
  "não quero decepcionar",
  "preciso continuar performando",
  "papel",
  "identidade",
  "não consigo desligar",
  "não saio do modo trabalho",
  "todo mundo precisa de mim",
  "trabajo",
  "cliente",
  "jefe",
  "equipo",
  "reunión",
  "plazo",
  "padre",
  "madre",
  "hijos",
  "familia",
  "responsabilidad",
  "expectativas",
  "presión",
  "no puedo permitirme bajar el ritmo",
  "siempre activo",
  "tengo que seguir rindiendo",
  "no puedo fallarles",
  "no quiero decepcionarles",
  "tengo que seguir cumpliendo",
  "rol",
  "identidad",
  "no puedo desconectar",
  "no salgo del modo trabajo",
  "todo el mundo me necesita"
];
  var meo = [
  "regret",
  "i regret",
  "i shouldn't have",
  "shouldn't have done that",
  "shouldn't have said that",
  "if only",
  "what if",
  "vague future",
  "future anxiety",
  "guilt of resting",
  "release the guilt",
  "past ghosts",
  "old mistake",
  "anxious thought",
  "small irritating",
  "minor spiral",
  "what if it happens",
  "what if something goes wrong",
  "i'm worried",
  "i worry",
  "worried about",
  "anxious about",
  "future",
  "the future",
  "later",
  "next week",
  "next month",
  "i can't control",
  "out of my control",
  "nothing i can do",
  "i can't change it",
  "too late now",
  "it already happened",
  "what's done is done",
  "i regret saying",
  "i regret doing",
  "it's too late",
  "i can't change it",
  "already happened",
  "i'm worried about the future",
  "i'm worried about tomorrow",
  "let go",
  "let this go",
  "release this",
  "release it",
  "move on",
  "need to move on",
  "can't stop holding onto it",
  "carrying this around",
  "lingering thought",
  "lingering feeling",
  "lingering stress",
  "mental residue",
  "thought residue",
  "emotional residue",
  "still stuck on it",
  "still thinking about it",
  "still carrying it",
  "can't shake it",
  "won't leave my head",
  "need closure",
  "need an ending",
  "need to put this down",
  "need to stop carrying this",
  "need to leave this behind",
  "want to drop it",
  "want to release it",
  "want to clear this out",
  "want this out of my head",
  "tired of thinking about it",
  "exhausted by this thought",
  "mentally holding onto it",
  "dragging this around mentally",
  "mentally heavy",
  "emotional weight",
  "carrying emotional weight",
  "carrying mental weight",
  "can't release it",
  "can't detach",
  "need to detach",
  "need distance from this",
  "want distance from this",
  "ready to let go",
  "trying to let go",
  "trying to release it",
  "trying to stop thinking about it",
  "trying to stop replaying it",
  "replaying it over and over",
  "replaying conversations",
  "replaying the moment",
  "replaying mistakes",
  "replaying memories",
  "overprocessing",
  "overthinking the past",
  "dwelling on it",
  "ruminating",
  "spiraling about the past",
  "emotional loop",
  "mental loop",
  "unresolved feeling",
  "unresolved thought",
  "unfinished feeling",
  "lingering attachment",
  "lingering memory",
  "need peace from this",
  "need relief from this",
  "need emotional release",
  "need mental release",
  "need to exhale mentally",
  "want this to fade",
  "want this to disappear",
  "want to stop revisiting this",
  "need help releasing this",
  "want to stop carrying this into tomorrow",
  "need a clean break",
  "need a reset from this",
  "need to free mental space",
  "freeing mental space",
  "clearing mental space",
  "clear this from my head",
  "need to stop feeding this thought",
  "no longer important",
  "maybe this doesn't need to stay with me",
  "i don't need to carry this anymore",
  "i can release this",
  "i want to release this",
  "i'm done holding onto this",
  "後悔",
  "後悔してる",
  "言わなきゃよかった",
  "やらなきゃよかった",
  "もしも",
  "もし〜だったら",
  "どうしよう",
  "どうなるんだろう",
  "心配",
  "不安",
  "将来",
  "未来",
  "この先",
  "来週",
  "来月",
  "コントロールできない",
  "どうにもできない",
  "変えられない",
  "もう終わったこと",
  "もう遅い",
  "仕方ない",
  "手放したい",
  "手放す",
  "これを手放す",
  "解放したい",
  "前に進みたい",
  "前に進む必要がある",
  "離せない",
  "ずっと引きずってる",
  "残り続ける思考",
  "残り続ける気持ち",
  "残り続けるストレス",
  "心の残り",
  "思考の残り",
  "感情の残り",
  "まだ引っかかってる",
  "まだ考えてしまう",
  "まだ抱えている",
  "振り切れない",
  "頭から離れない",
  "区切りがほしい",
  "終わりがほしい",
  "下ろしたい",
  "抱え続けるのをやめたい",
  "後ろに残したい",
  "落としたい",
  "頭を空にしたい",
  "頭から消したい",
  "考えるのに疲れた",
  "この思考に疲れた",
  "心で抱え続けている",
  "心で引きずっている",
  "心が重い",
  "感情の重さ",
  "感情の重荷",
  "心の重荷",
  "解放できない",
  "切り離せない",
  "距離がほしい",
  "距離を取りたい",
  "手放す準備ができた",
  "手放そうとしてる",
  "解放しようとしてる",
  "考えるのを止めようとしてる",
  "再生するのを止めようとしてる",
  "何度も再生してしまう",
  "会話を再生",
  "あの瞬間を再生",
  "失敗を再生",
  "記憶を再生",
  "考えすぎ",
  "過去を考えすぎ",
  "引きずり",
  "反芻",
  "過去についてぐるぐる",
  "感情のループ",
  "思考のループ",
  "未解決の感情",
  "未解決の思考",
  "未完了の感情",
  "残り続ける執着",
  "残り続ける記憶",
  "このことから平穏がほしい",
  "このことから解放がほしい",
  "感情の解放がほしい",
  "心の解放がほしい",
  "心で吐息をつきたい",
  "薄れたい",
  "消えてほしい",
  "また思い出すのを止めたい",
  "手放すのを手伝って",
  "明日まで抱え込みたくない",
  "区切りがほしい",
  "リセットがほしい",
  "心のスペースを空けたい",
  "心のスペースを空ける",
  "頭の中をクリアしたい",
  "この思考にエネルギーを注ぐのをやめたい",
  "もう大切じゃない",
  "もう私と一緒にいなくていい",
  "もう抱えなくていい",
  "手放せる",
  "もう抱え続けるのは終わり",
  "reue",
  "ich bereue",
  "hätte ich doch",
  "ich hätte nicht",
  "wenn doch",
  "was wenn",
  "was wäre wenn",
  "ich mache mir sorgen",
  "sorge",
  "besorgt",
  "zukunft",
  "die zukunft",
  "nächste woche",
  "nächsten monat",
  "ich kann es nicht kontrollieren",
  "außerhalb meiner kontrolle",
  "ich kann nichts tun",
  "ich kann es nicht ändern",
  "zu spät",
  "es ist schon passiert",
  "geschehen ist geschehen",
  "loslassen",
  "das loslassen",
  "freisetzen",
  "weitergehen",
  "weitergehen müssen",
  "kann es nicht loslassen",
  "schleppe das mit",
  "hängender gedanke",
  "hängendes gefühl",
  "hängender stress",
  "geistige reste",
  "gedankenreste",
  "emotionale reste",
  "hänge noch dran",
  "denke noch daran",
  "trage es noch mit",
  "kann es nicht abschütteln",
  "brauche abschluss",
  "brauche ein ende",
  "muss das ablegen",
  "muss aufhören das mitzutragen",
  "muss das hinter mir lassen",
  "will es fallen lassen",
  "will es loslassen",
  "will es aus dem kopf",
  "müde vom nachdenken",
  "erschöpft von diesem gedanken",
  "halte es geistig fest",
  "schleppe es geistig mit",
  "geistig schwer",
  "emotionales gewicht",
  "emotionale last",
  "geistige last",
  "kann es nicht freigeben",
  "kann mich nicht lösen",
  "brauche distanz",
  "will distanz",
  "bereit loszulassen",
  "versuche loszulassen",
  "versuche es freizugeben",
  "versuche aufzuhören daran zu denken",
  "versuche aufzuhören es abzuspulen",
  "spule es immer wieder ab",
  "spiele gespräche ab",
  "spiele den moment ab",
  "spiele fehler ab",
  "spiele erinnerungen ab",
  "überverarbeiten",
  "über die vergangenheit grübeln",
  "verweile daran",
  "spirale über die vergangenheit",
  "emotionale schleife",
  "ungelöstes gefühl",
  "ungelöster gedanke",
  "unvollständiges gefühl",
  "hängende bindung",
  "hängende erinnerung",
  "brauche frieden davon",
  "brauche erleichterung davon",
  "brauche emotionalen release",
  "brauche geistigen release",
  "geistig ausatmen",
  "will dass es verblasst",
  "will dass es verschwindet",
  "will aufhören es zu besuchen",
  "brauche hilfe beim loslassen",
  "will es nicht bis morgen mittragen",
  "brauche einen klaren schnitt",
  "brauche einen reset davon",
  "geistigen raum freimachen",
  "kopf freimachen",
  "aus meinem kopf löschen",
  "muss aufhören diesen gedanken zu füttern",
  "nicht mehr wichtig",
  "muss das nicht mehr tragen",
  "ich kann das loslassen",
  "ich will das loslassen",
  "ich bin fertig damit es festzuhalten",
  "후회",
  "후회해",
  "그러지 말걸",
  "말하지 말걸",
  "만약",
  "만약에",
  "어떡하지",
  "어떻게 될까",
  "걱정",
  "불안",
  "미래",
  "앞으로",
  "다음 주",
  "다음 달",
  "내가 통제할 수 없어",
  "어쩔 수 없어",
  "바꿀 수 없어",
  "이미 일어났어",
  "이미 지나갔어",
  "늦었어",
  "놓아주고 싶어",
  "놓아줘",
  "이걸 놓아주고 싶어",
  "해방하고 싶어",
  "앞으로 나아가고 싶어",
  "앞으로 나아가야 해",
  "놓지 못해",
  "계속 끌고 다녀",
  "남아 있는 생각",
  "남아 있는 감정",
  "남아 있는 스트레스",
  "마음의 찌꺼기",
  "생각의 찌꺼기",
  "감정의 찌꺼기",
  "아직 붙잡고 있어",
  "아직 생각 중이야",
  "아직 안고 있어",
  "떨쳐내지 못해",
  "마무리가 필요해",
  "끝이 필요해",
  "내려놓아야 해",
  "계속 안고 다니는 걸 멈춰야 해",
  "뒤에 남겨야 해",
  "떨어뜨리고 싶어",
  "머리를 비우고 싶어",
  "머리에서 지우고 싶어",
  "생각하기 지쳤어",
  "이 생각에 지쳤어",
  "마음으로 붙잡고 있어",
  "마음으로 끌고 다녀",
  "마음이 무거워",
  "감정의 무게",
  "감정적 짐",
  "정신적 짐",
  "놓아줄 수 없어",
  "떨어질 수 없어",
  "거리가 필요해",
  "거리를 두고 싶어",
  "놓을 준비가 됐어",
  "놓으려고 해",
  "해방하려고 해",
  "생각하는 걸 멈추려고 해",
  "되감는 걸 멈추려고 해",
  "계속 되감아",
  "대화를 되감아",
  "그 순간을 되감아",
  "실수를 되감아",
  "기억을 되감아",
  "과잉 처리",
  "과거를 너무 생각해",
  "집착해",
  "과거에 대해 소용돌이",
  "감정 루프",
  "생각 루프",
  "미해결 감정",
  "미해결 생각",
  "미완 감정",
  "남아 있는 집착",
  "남아 있는 기억",
  "이것에서 평화가 필요해",
  "이것에서 해방이 필요해",
  "감정적 해방이 필요해",
  "정신적 해방이 필요해",
  "마음으로 숨 내쉬고 싶어",
  "희미해지길 원해",
  "사라지길 원해",
  "다시 떠올리는 걸 멈추고 싶어",
  "놓는 걸 도와줘",
  "내일까지 안고 가고 싶지 않아",
  "깔끔한 단절이 필요해",
  "리셋이 필요해",
  "마음 공간을 비우고 싶어",
  "마음 공간 비우기",
  "머릿속을 비우고 싶어",
  "이 생각에 에너지 주는 걸 멈춰야 해",
  "더 이상 중요하지 않아",
  "더 이상 안고 다닐 필요 없어",
  "놓을 수 있어",
  "더 이상 붙잡고 있지 않을 거야",
  "regret",
  "je regrette",
  "j'aurais dû",
  "je n'aurais pas dû",
  "si seulement",
  "et si",
  "et si ça arrive",
  "je m'inquiète",
  "inquiet",
  "anxieux",
  "avenir",
  "le futur",
  "semaine prochaine",
  "mois prochain",
  "je ne peux pas contrôler",
  "hors de mon contrôle",
  "je ne peux rien faire",
  "je ne peux pas changer",
  "trop tard",
  "c'est déjà arrivé",
  "ce qui est fait est fait",
  "lâcher prise",
  "laisser partir",
  "libérer ça",
  "libérer",
  "passer à autre chose",
  "besoin de passer à autre chose",
  "n'arrive pas à lâcher",
  "je traîne ça avec moi",
  "pensée persistante",
  "sentiment persistant",
  "stress persistant",
  "résidu mental",
  "résidu de pensée",
  "résidu émotionnel",
  "encore accroché",
  "j'y pense encore",
  "je le porte encore",
  "n'arrive pas à m'en défaire",
  "besoin de clôture",
  "besoin d'une fin",
  "besoin de poser ça",
  "besoin d'arrêter de porter ça",
  "besoin de laisser ça derrière",
  "veux le lâcher",
  "veux le libérer",
  "veux vider ma tête",
  "veux l'effacer de ma tête",
  "fatigué d'y penser",
  "épuisé par cette pensée",
  "je le retiens mentalement",
  "je le traîne mentalement",
  "lourd mentalement",
  "poids émotionnel",
  "poids mental",
  "n'arrive pas à libérer",
  "n'arrive pas à me détacher",
  "besoin de distance",
  "veux de la distance",
  "prêt à lâcher",
  "j'essaie de lâcher",
  "j'essaie de libérer",
  "j'essaie d'arrêter d'y penser",
  "j'essaie d'arrêter de rejouer",
  "je le rejoue encore et encore",
  "rejouer des conversations",
  "rejouer le moment",
  "rejouer des erreurs",
  "rejouer des souvenirs",
  "surtraiter",
  "trop penser au passé",
  "spirale sur le passé",
  "boucle émotionnelle",
  "boucle mentale",
  "sentiment non résolu",
  "pensée non résolue",
  "sentiment inachevé",
  "attachement persistant",
  "souvenir persistant",
  "besoin de paix avec ça",
  "besoin de soulagement",
  "besoin de libération émotionnelle",
  "besoin de libération mentale",
  "expirer mentalement",
  "veux que ça s'estompe",
  "veux que ça disparaisse",
  "veux arrêter d'y revenir",
  "besoin d'aide pour lâcher",
  "ne veux pas porter ça jusqu'à demain",
  "besoin d'une coupure nette",
  "besoin d'un reset",
  "libérer de l'espace mental",
  "vider l'espace mental",
  "effacer ça de ma tête",
  "dois arrêter d'alimenter cette pensée",
  "plus important",
  "n'ai plus besoin de porter ça",
  "je peux libérer ça",
  "je veux libérer ça",
  "j'en ai fini de m'y accrocher",
  "arrependimento",
  "me arrependo",
  "eu não devia ter",
  "se ao menos",
  "e se",
  "e se acontecer",
  "estou preocupado",
  "preocupação",
  "ansioso",
  "futuro",
  "o futuro",
  "semana que vem",
  "mês que vem",
  "não posso controlar",
  "fora do meu controle",
  "não posso fazer nada",
  "não posso mudar",
  "tarde demais",
  "já aconteceu",
  "o que foi feito está feito",
  "soltar",
  "deixar ir",
  "liberar isso",
  "liberar",
  "seguir em frente",
  "preciso seguir em frente",
  "não consigo soltar",
  "carregando isso",
  "pensamento persistente",
  "sentimento persistente",
  "estresse persistente",
  "resíduo mental",
  "resíduo de pensamento",
  "resíduo emocional",
  "ainda preso nisso",
  "ainda pensando nisso",
  "ainda carregando",
  "não consigo sacudir",
  "preciso de encerramento",
  "preciso de um fim",
  "preciso largar isso",
  "preciso parar de carregar",
  "preciso deixar isso para trás",
  "quero soltar",
  "quero liberar",
  "quero limpar a cabeça",
  "quero tirar da cabeça",
  "cansado de pensar nisso",
  "exausto por esse pensamento",
  "segurando mentalmente",
  "arrastando mentalmente",
  "mentalmente pesado",
  "peso emocional",
  "peso mental",
  "não consigo liberar",
  "não consigo me desapegar",
  "preciso de distância",
  "quero distância",
  "pronto para soltar",
  "tentando soltar",
  "tentando liberar",
  "tentando parar de pensar",
  "tentando parar de repassar",
  "repassando de novo e de novo",
  "repassando conversas",
  "repassando o momento",
  "repassando erros",
  "repassando memórias",
  "processando demais",
  "pensando demais no passado",
  "espiral sobre o passado",
  "loop emocional",
  "loop mental",
  "sentimento não resolvido",
  "pensamento não resolvido",
  "sentimento inacabado",
  "apego persistente",
  "memória persistente",
  "preciso de paz com isso",
  "preciso de alívio",
  "preciso de liberação emocional",
  "preciso de liberação mental",
  "expirar mentalmente",
  "quero que desapareça",
  "quero parar de revisitar",
  "preciso de ajuda para soltar",
  "não quero carregar isso até amanhã",
  "preciso de um corte limpo",
  "preciso de um reset",
  "liberar espaço mental",
  "limpando espaço mental",
  "limpar da cabeça",
  "preciso parar de alimentar esse pensamento",
  "não é mais importante",
  "não preciso mais carregar",
  "posso liberar isso",
  "quero liberar isso",
  "terminei de segurar isso",
  "arrepentimiento",
  "me arrepiento",
  "no debería haber",
  "si hubiera",
  "y si",
  "y si pasa",
  "me preocupa",
  "preocupado",
  "ansioso",
  "futuro",
  "el futuro",
  "la semana que viene",
  "el mes que viene",
  "no puedo controlarlo",
  "fuera de mi control",
  "no puedo hacer nada",
  "no puedo cambiarlo",
  "demasiado tarde",
  "ya pasó",
  "lo hecho hecho está",
  "soltar",
  "dejar ir",
  "liberar esto",
  "liberar",
  "seguir adelante",
  "necesito seguir adelante",
  "no puedo soltarlo",
  "cargando con esto",
  "pensamiento persistente",
  "sentimiento persistente",
  "estrés persistente",
  "residuo mental",
  "residuo de pensamiento",
  "residuo emocional",
  "aún atrapado en ello",
  "sigo pensando en ello",
  "sigo cargándolo",
  "no puedo sacudírmelo",
  "necesito cierre",
  "necesito un final",
  "necesito dejarlo",
  "necesito dejar de cargarlo",
  "necesito dejarlo atrás",
  "quiero soltarlo",
  "quiero liberarlo",
  "quiero vaciar la cabeza",
  "quiero sacarlo de mi cabeza",
  "cansado de pensarlo",
  "agotado por este pensamiento",
  "sosteniéndolo mentalmente",
  "arrastrándolo mentalmente",
  "mentalmente pesado",
  "peso emocional",
  "peso mental",
  "no puedo liberarlo",
  "no puedo desprenderme",
  "necesito distancia",
  "quiero distancia",
  "listo para soltar",
  "intentando soltar",
  "intentando liberar",
  "intentando dejar de pensar",
  "intentando dejar de repetir",
  "repitiéndolo una y otra vez",
  "repitiendo conversaciones",
  "repitiendo el momento",
  "repitiendo errores",
  "repitiendo recuerdos",
  "sobreprocesar",
  "pensar demasiado el pasado",
  "espiral sobre el pasado",
  "bucle emocional",
  "bucle mental",
  "sentimiento no resuelto",
  "pensamiento no resuelto",
  "sentimiento incompleto",
  "apego persistente",
  "memoria persistente",
  "necesito paz con esto",
  "necesito alivio",
  "necesito liberación emocional",
  "necesito liberación mental",
  "exhalar mentalmente",
  "quiero que se desvanezca",
  "quiero que desaparezca",
  "quiero dejar de revisitarlo",
  "necesito ayuda para soltar",
  "no quiero cargarlo hasta mañana",
  "necesito un corte limpio",
  "necesito un reinicio",
  "liberar espacio mental",
  "vaciando espacio mental",
  "limpiar de mi cabeza",
  "debo dejar de alimentar este pensamiento",
  "ya no importa",
  "ya no necesito cargarlo",
  "puedo liberarlo",
  "quiero liberarlo",
  "terminé de aferrarme a esto"
];
  var backyard = [
  "can't focus but don't want to work",
  "scrolling without thinking",
  "switching apps constantly",
  "opening apps over and over",
  "checking things repeatedly",
  "can't stop scrolling",
  "jumping between apps",
  "bouncing around",
  "scrolling again",
  "itchy brain",
  "itchy attention",
  "restless energy",
  "brain noise",
  "mental static",
  "mind wandering",
  "need somewhere to go",
  "need something to do",
  "need stimulation",
  "can't sit still",
  "doomscrolling",
  "restless",
  "antsy",
  "fidgety",
  "itchy",
  "wandering",
  "drifting",
  "don't want to start yet",
  "not ready yet",
  "putting it off",
  "circling around it",
  "wandering online",
  "opening random apps",
  "clicking around",
  "killing time",
  "wasting time",
  "procrastinating",
  "avoiding",
  "stalling",
  "hovering",
  "hanging around",
  "lurking",
  "idling",
  "doing nothing feels weird",
  "silence feels loud",
  "need something in the background",
  "need background noise",
  "need to zone out a bit",
  "need to decompress",
  "can't fully rest",
  "brain too active",
  "mentally buzzing",
  "understimulated",
  "can't settle",
  "can't relax",
  "too quiet",
  "want ambient interaction",
  "need low effort stimulation",
  "just want to poke around",
  "want something interactive",
  "need sensory input",
  "need movement",
  "want to explore",
  "want to wander",
  "need tactile",
  "fidget",
  "nothing feels engaging",
  "everything feels boring",
  "cycling through apps",
  "stuck online",
  "staring at screen",
  "refreshing",
  "i just need somewhere to wander",
  "i don't want to think right now",
  "i need a mental hallway",
  "i want to drift for a bit",
  "i need background movement",
  "i don't want goals right now",
  "i don't want to do anything serious",
  "i just want to disappear for a second",
  "i need a buffer space",
  "仕事したくないのに集中できない",
  "無意識にスクロール",
  "アプリを次々切り替える",
  "何度もアプリを開く",
  "何度も確認する",
  "スクロールが止まらない",
  "アプリを行ったり来たり",
  "うろうろ",
  "またスクロール",
  "ムズムズする頭",
  "落ち着かない注意",
  "落ち着かないエネルギー",
  "頭のノイズ",
  "心の雑音",
  "思考がさ迷う",
  "行き場がほしい",
  "何かしたい",
  "刺激がほしい",
  "じっとしていられない",
  "ドゥームスクロール",
  "落ち着かない",
  "そわそわ",
  "もじもじ",
  "ムズムズ",
  "さ迷う",
  "漂う",
  "まだ始めたくない",
  "まだ準備できてない",
  "先延ばし",
  "ぐるぐる回ってる",
  "ネットをうろうろ",
  "ランダムにアプリを開く",
  "クリックばかり",
  "時間つぶし",
  "時間の無駄",
  "先延ばししてる",
  "避けてる",
  "停滞",
  "うろついてる",
  "ぶらぶら",
  "潜ってる",
  "アイドル",
  "何もしないのが変",
  "静寂がうるさい",
  "背景音がほしい",
  "背景ノイズがほしい",
  "少しゾーンアウトしたい",
  "一息つきたい",
  "完全に休めない",
  "脳が活発すぎる",
  "頭がうずうず",
  "刺激不足",
  "落ち着けない",
  "リラックスできない",
  "静かすぎる",
  "環境的な操作がほしい",
  "低負荷の刺激がほしい",
  "ちょっと触り回したい",
  "インタラクティブなものがほしい",
  "感覚入力がほしい",
  "動きがほしい",
  "探索したい",
  "ぶらつきたい",
  "触覚がほしい",
  "フィジット",
  "何も面白くない",
  "全部つまらない",
  "アプリを巡回",
  "オンラインに閉じ込め",
  "画面を見つめる",
  "更新ばかり",
  "ぶらつく場所がほしい",
  "今は考えたくない",
  "心の廊下がほしい",
  "少し漂いたい",
  "背景の動きがほしい",
  "今は目標がほしくない",
  "真剣なことはしたくない",
  "一瞬消えたい",
  "バッファスペースがほしい",
  "kann mich nicht konzentrieren will aber nicht arbeiten",
  "gedankenlos scrollen",
  "ständig apps wechseln",
  "apps immer wieder öffnen",
  "ständig nachschauen",
  "kann nicht aufhören zu scrollen",
  "springe zwischen apps",
  "hüpfe rum",
  "wieder scrollen",
  "juckendes gehirn",
  "unruhige aufmerksamkeit",
  "unruhige energie",
  "kopflärm",
  "geistiges rauschen",
  "gedanken wandern",
  "brauche irgendwo hin",
  "brauche etwas zu tun",
  "brauche stimulation",
  "kann nicht stillsitzen",
  "doomscrollen",
  "unruhig",
  "zappelig",
  "zappeln",
  "juckig",
  "wandern",
  "treiben",
  "will noch nicht anfangen",
  "noch nicht bereit",
  "schiebe es auf",
  "kreise drum herum",
  "irgendwo online wandern",
  "zufällige apps öffnen",
  "klicke rum",
  "zeit totschlagen",
  "zeit verschwenden",
  "prokrastiniere",
  "vermeide",
  "zögere",
  "schwebe rum",
  "hänge rum",
  "lurk",
  "idle",
  "nichts tun fühlt sich komisch an",
  "stille ist laut",
  "brauche etwas im hintergrund",
  "brauche hintergrundgeräusch",
  "muss ein bisschen abschalten",
  "muss abschalten",
  "kann nicht richtig ruhen",
  "gehirn zu aktiv",
  "geistig summend",
  "unterstimuliert",
  "kann mich nicht beruhigen",
  "kann mich nicht entspannen",
  "zu ruhig",
  "will ambiente interaktion",
  "brauche wenig anstrengende stimulation",
  "will nur rumstöbern",
  "will etwas interaktives",
  "brauche sensorischen input",
  "brauche bewegung",
  "will erkunden",
  "will wandern",
  "brauche taktil",
  "fidget",
  "nichts fühlt sich ansprechend an",
  "alles langweilig",
  "apps durchwechseln",
  "online feststecken",
  "starre auf den bildschirm",
  "aktualisiere ständig",
  "brauche nur irgendwo zum wandern",
  "will jetzt nicht denken",
  "brauche einen geistigen flur",
  "will ein bisschen treiben",
  "brauche hintergrundbewegung",
  "will jetzt keine ziele",
  "will nichts ernstes tun",
  "will für eine sekunde verschwinden",
  "brauche einen pufferraum",
  "일하기 싫은데 집중이 안 돼",
  "생각 없이 스크롤",
  "앱을 계속 바꿔",
  "앱을 계속 열어",
  "계속 확인해",
  "스크롤을 멈출 수 없어",
  "앱 사이를 왔다 갔다",
  "뛰어다녀",
  "또 스크롤",
  "간지러운 머리",
  "안절부절한 주의",
  "안절부절한 에너지",
  "머리 소음",
  "정신적 잡음",
  "마음이 방황",
  "갈 곳이 필요해",
  "뭔가 해야 해",
  "자극이 필요해",
  "가만히 못 있어",
  "둠스크롤",
  "안절부절",
  "들떠",
  "꼼지락",
  "간지러워",
  "방황",
  "표류",
  "아직 시작하기 싫어",
  "아직 준비 안 됐어",
  "미루고 있어",
  "맴돌고 있어",
  "온라인을 방황",
  "아무 앱이나 열어",
  "클릭만 해",
  "시간 때우기",
  "시간 낭비",
  "미루기",
  "피하고 있어",
  "주저",
  "서성",
  "어슬렁",
  "잠복",
  "유휴",
  "아무것도 안 하면 이상해",
  "침묵이 시끄러워",
  "배경음이 필요해",
  "배경 소음 필요",
  "조금 멍 때리고 싶어",
  "긴장 풀고 싶어",
  "완전히 쉴 수 없어",
  "뇌가 너무 활발",
  "머리가 윙윙",
  "자극 부족",
  "가라앉지 못해",
  "긴장 풀 수 없어",
  "너무 조용해",
  "주변 상호작용 원해",
  "낮은 노력 자극 필요",
  "그냥 둘러보고 싶어",
  "인터랙티브한 게 필요해",
  "감각 입력 필요",
  "움직임 필요",
  "탐색하고 싶어",
  "돌아다니고 싶어",
  "촉각 필요",
  "피젯",
  "아무것도 재미없어",
  "다 지루해",
  "앱 순환",
  "온라인에 갇혀",
  "화면 응시",
  "새로고침만",
  "돌아다닐 곳이 필요해",
  "지금은 생각하기 싫어",
  "마음의 복도 필요",
  "잠깐 표류하고 싶어",
  "배경 움직임 필요",
  "지금은 목표 원하지 않아",
  "진지한 건 하기 싫어",
  "잠깐 사라지고 싶어",
  "완충 공간 필요",
  "je n'arrive pas à me concentrer mais je ne veux pas travailler",
  "scroll sans réfléchir",
  "change d'apps constamment",
  "ouvre les apps encore et encore",
  "vérifie sans arrêt",
  "n'arrive pas à arrêter de scroller",
  "saute entre les apps",
  "fais des allers-retours",
  "encore scroller",
  "cerveau qui gratte",
  "attention agitée",
  "énergie agitée",
  "bruit mental",
  "static mental",
  "esprit qui vagabonde",
  "besoin d'aller quelque part",
  "besoin de faire quelque chose",
  "besoin de stimulation",
  "n'arrive pas à rester assis",
  "doomscroll",
  "agité",
  "impatient",
  "gigote",
  "gratte",
  "errer",
  "dériver",
  "ne veux pas encore commencer",
  "pas encore prêt",
  "je remets",
  "tourne autour",
  "erre en ligne",
  "ouvre des apps au hasard",
  "clique partout",
  "tuer le temps",
  "perdre du temps",
  "procrastine",
  "j'évite",
  "j'hésite",
  "je rôde",
  "je traîne",
  "je lurke",
  "inactif",
  "ne rien faire est bizarre",
  "le silence est fort",
  "besoin de quelque chose en fond",
  "besoin de bruit de fond",
  "besoin de décrocher un peu",
  "besoin de décompresser",
  "ne peux pas vraiment me reposer",
  "cerveau trop actif",
  "bourdonnement mental",
  "sous-stimulé",
  "n'arrive pas à m'installer",
  "n'arrive pas à me détendre",
  "trop calme",
  "veux une interaction ambient",
  "besoin de stimulation facile",
  "veux juste fouiller",
  "veux quelque chose d'interactif",
  "besoin d'input sensoriel",
  "besoin de mouvement",
  "veux explorer",
  "veux errer",
  "besoin de tactile",
  "fidget",
  "rien n'engage",
  "tout est ennuyeux",
  "fais le tour des apps",
  "coincé en ligne",
  "fixe l'écran",
  "rafraîchis sans arrêt",
  "j'ai juste besoin d'errer quelque part",
  "je ne veux pas penser maintenant",
  "j'ai besoin d'un couloir mental",
  "je veux dériver un peu",
  "j'ai besoin de mouvement en fond",
  "je ne veux pas d'objectifs maintenant",
  "je ne veux rien de sérieux",
  "je veux disparaître une seconde",
  "j'ai besoin d'un espace tampon",
  "não consigo focar mas não quero trabalhar",
  "rolando sem pensar",
  "trocando de apps o tempo todo",
  "abrindo apps de novo e de novo",
  "checando repetidamente",
  "não consigo parar de rolar",
  "pulando entre apps",
  "pulando de um lado pro outro",
  "rolando de novo",
  "cérebro coçando",
  "atenção inquieta",
  "energia inquieta",
  "ruído mental",
  "estática mental",
  "mente vagando",
  "preciso de algum lugar pra ir",
  "preciso fazer algo",
  "preciso de estímulo",
  "não consigo ficar parado",
  "doomscroll",
  "inquieto",
  "ansioso",
  "inquieto",
  "coceira",
  "vagando",
  "derivando",
  "não quero começar ainda",
  "não estou pronto",
  "procrastinando",
  "circulando em volta",
  "vagando online",
  "abrindo apps aleatórios",
  "clicando por aí",
  "matando tempo",
  "perdendo tempo",
  "procrastinando",
  "evitando",
  "enrolando",
  "rondando",
  "hangueando",
  "lurking",
  "ocioso",
  "não fazer nada é estranho",
  "silêncio é alto",
  "preciso de algo no fundo",
  "preciso de barulho de fundo",
  "preciso desligar um pouco",
  "preciso descompressar",
  "não consigo descansar de verdade",
  "cérebro muito ativo",
  "zumbindo mentalmente",
  "subestimulado",
  "não consigo me acalmar",
  "não consigo relaxar",
  "quieto demais",
  "quero interação ambiente",
  "preciso de estímulo de baixo esforço",
  "só quero fuçar",
  "quero algo interativo",
  "preciso de input sensorial",
  "preciso de movimento",
  "quero explorar",
  "quero vagar",
  "preciso de tátil",
  "fidget",
  "nada parece envolvente",
  "tudo parece chato",
  "ciclando apps",
  "preso online",
  "olhando a tela",
  "atualizando",
  "só preciso de algum lugar pra vagar",
  "não quero pensar agora",
  "preciso de um corredor mental",
  "quero derivar um pouco",
  "preciso de movimento de fundo",
  "não quero metas agora",
  "não quero nada sério",
  "só quero sumir por um segundo",
  "preciso de um espaço buffer",
  "no puedo concentrarme pero no quiero trabajar",
  "scrolleando sin pensar",
  "cambiando de apps constantemente",
  "abriendo apps una y otra vez",
  "comprobando repetidamente",
  "no puedo dejar de scrollear",
  "saltando entre apps",
  "rebotando",
  "scrolleando otra vez",
  "cerebro que pica",
  "atención inquieta",
  "energía inquieta",
  "ruido mental",
  "estática mental",
  "mente divagando",
  "necesito ir a algún sitio",
  "necesito hacer algo",
  "necesito estimulación",
  "no puedo quedarme quieto",
  "doomscroll",
  "inquieto",
  "inquieto",
  "inquieto",
  "picor",
  "deambulando",
  "derivando",
  "no quiero empezar todavía",
  "no estoy listo",
  "lo estoy posponiendo",
  "dando vueltas",
  "deambulando online",
  "abriendo apps al azar",
  "haciendo clic por ahí",
  "matando el tiempo",
  "perdiendo el tiempo",
  "procrastinando",
  "evitando",
  "dudando",
  "rondando",
  "merodeando",
  "acechando",
  "ocioso",
  "no hacer nada se siente raro",
  "el silencio es fuerte",
  "necesito algo de fondo",
  "necesito ruido de fondo",
  "necesito desconectar un poco",
  "necesito descomprimir",
  "no puedo descansar del todo",
  "cerebro demasiado activo",
  "zumbido mental",
  "infraestimulado",
  "no puedo calmarme",
  "no puedo relajarme",
  "demasiado silencio",
  "quiero interacción ambiental",
  "necesito estimulación de bajo esfuerzo",
  "solo quiero curiosear",
  "quiero algo interactivo",
  "necesito input sensorial",
  "necesito movimiento",
  "quiero explorar",
  "quiero deambular",
  "necesito táctil",
  "fidget",
  "nada parece interesante",
  "todo parece aburrido",
  "ciclando apps",
  "atrapado online",
  "mirando la pantalla",
  "actualizando",
  "solo necesito un sitio donde deambular",
  "no quiero pensar ahora",
  "necesito un pasillo mental",
  "quiero derivar un poco",
  "necesito movimiento de fondo",
  "no quiero metas ahora",
  "no quiero nada serio",
  "solo quiero desaparecer un segundo",
  "necesito un espacio buffer"
];

  return {
    mfo: mfo,
    mso: mso,
    mzo: mzo,
    mbo: mbo,
    meo: meo,
    backyard: backyard
  };
})();
